### ISSUE TITLE
Endpoint.singleEntryUrl must be "uri-template" not "uri"

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/beacon-v2#103]
Hello,

In the [beaconMapResponse](https://github.com/ga4gh-beacon/beacon-v2/blob/main/framework/json/responses/beaconMapResponse.json) (/map) there are some endpoint URLs that are defined as `"format": "uri"` while what is actually put / expected `"format": "uri-template"`.
For instance, [Endpoint.singleEntryUrl](https://github.com/ga4gh-beacon/beacon-v2/blob/d2be0e2fcc4cbbaebb355caaf8a20af25504a687/framework/json/configuration/beaconMapSchema.json#L35) expects the entry identifier. Also additional endpoints should be corrected[RealatedEndpoint.url](https://github.com/ga4gh-beacon/beacon-v2/blob/d2be0e2fcc4cbbaebb355caaf8a20af25504a687/framework/json/configuration/beaconMapSchema.json#L53) .

Currently strict Json Schema Validator reports errors on all endpoints that have path parameters {}.

Cheers,

Dmitry

**Comment by costero-e** [comment]
For the endpoints that include parameters that must be resolved, like individuals/{id) it should be `uri-template` if we are accurate, yes. 

Best,

Oriol

**Comment by jrambla** [comment]
@redmitry should we consider this a breaking change or just a bug correction?

**Comment by redmitry** [comment]
Not critical bug correction.
Draft 7 validators should fail validating `"singleEntryUrl": "https://beacons.bsc.es/beacon/v2.0.0/datasets/{id}"` because "{}" characters forbidden in URI.  
On the other hand in 2020-12 "format" property shouldn't be considered by default (should be ignored).
The question whether we want to enable "format" validation in 2020-12 and if validator used in beacon validator.
1. may be programmatically configured to enable "format" vaildation.
2. understand "vocabulary" way to enable "format" validation via JSON schema mechanism.

D.

**Comment by costero-e** [comment]
Closing as this has been merged in #110.
