### ISSUE TITLE
Invalid timeElement schema

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/beacon-v2#112]
Hi all,

The [timeElement.json](https://github.com/ga4gh-beacon/beacon-v2/blob/main/models/json/beacon-v2-default-model/common/timeElement.json) which is the `oneOf`  of
- age.json
- ageRange.json
- gestationalAge.json
- commonDefinitions.json#/definitions/Timestamp
- timeInterval.json
- ontologyTerm.json

Will always fail to validate because of very permissive "age" and "ageRange" that have no "required" properties defined.

Cheers,

Dmitry

**Comment by delocalizer** [comment]
Thanks for #113 and looking forward to the merge; this exact bug is biting me today
```
jsonschema.exceptions.ValidationError: {'age': {'iso8601duration': 'P30Y'}} is valid under each of {'$ref': './ageRange.json'}, {'$ref': './age.json'}

...
```

**Comment by redmitry** [comment]
Resolved. Merged.
