### ISSUE TITLE
Conflicting `filteringTerms` definition in `genomicVariations`

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/beacon-v2#159]
While for other entities  in the `filteringTerms.yaml/json` files no values are provided, in [`.../genomicVariations filteringTerms.yaml`](https://github.com/ga4gh-beacon/beacon-v2/tree/main/models/src/beacon-v2-default-model/genomicVariations/filteringTerms.yaml) there is an odd entry for 2 alphanumeric filters:

```
filteringTerms:
  - ftType: alphanumeric
    id: gene
  - ftType: alphanumeric
    id: aminoacidChanges
```

This is very problematic and misleading since:

- both "filters" have dedicated and documented query parameters ([`geneId`](https://github.com/ga4gh-beacon/beacon-v2/blob/16862205c79294fae5473f7fa330bf5929b3b120/models/src/beacon-v2-default-model/genomicVariations/requestParameters.yaml#L102) and [`aminoacidChange`](https://github.com/ga4gh-beacon/beacon-v2/blob/16862205c79294fae5473f7fa330bf5929b3b120/models/src/beacon-v2-default-model/genomicVariations/requestParameters.yaml#L111))
- the definition of filtering terms here is _exceptional_ and in contrast to the common use (leave the filter definition to implementations)
- a definition here could be perceived as "only those values are permitted"

**Proposal** Remove in hot fix to avoid further confusion.

**Comment by gsfk** [comment]
+1 for this.

I also see non-empty filteringTerms.yaml files for cohorts and datasets. They're not at bad as this one, but it's not clear what they're for.

**Comment by zykonda** [comment]
+1 for this, cohorts and datasets.
Both gene and aminoacidChanges in filtering terms look like code refactoring left over.

**Comment by mbaudis** [comment]
This has ben resolved in https://github.com/ga4gh-beacon/beacon-v2/pull/167 and should end up in main ASAP.
