### ISSUE TITLE
Use of Ensembl Glossary Variant Consequence in beacon2

### ISSUE THREAD

**Issue by andrewyatz** [ga4gh-beacon/beacon-v2#16]
Hi there. I've been reviewing beacon2 ahead of the GA4GH SC meeting and I was surprised to see beacon refers to ENSGLOSSARY as a source of terms to describe `molecularEffects`. I feel I have a duty to say ENSGLOSSARY was never intended to be used extensively outside of Ensembl. It is very much an Ensembl view of the world. The major consequence prediction tools including Ensembl VEP spent quite a bit of time aligning consequence terms in `SO`. For instance `ENSGLOSSARY:0000140` or `Transcript ablation` whilst has an `is_a` relationship to `Variant consequence` it has an xref to `SO:0001893`/`transcript_ablation`. 

There might be a reason you chose the Ensembl Glossary but I would urge looking towards sequence ontology to ensure tool/provider portability.

**Comment by jrambla** [comment]
Thanks for raising that @andrewyatz.
I was probably the one picking such ontology: I trust Ensembl!   ;-)
If the Ensembl view is a "real-world view" (~real world data) it would probably match the Beacon view, as we try to make the entering effort low and close to the view of the "lay genomicist"
I will take a look, but probably need help from experts like you or @mbaudis

**Comment by andrewyatz** [comment]
We are really glad you trust Ensembl. I think my issue is more that the ENSGLOSSARY ontology isn't really modelling real world concepts per say but modelling how Ensembl wants to think about the world. There are terms in there that are not part of our molecular consequence reporting. For that I would point you towards https://www.ensembl.org/info/genome/variation/prediction/predicted_data.html and you'll see that the consequence VEP predicts have their equivalent SO terms.

For future reference we, Ensembl, will also move our key concepts into a more dependable suite of value sets which would be used both internally by Ensembl and intended for external use. This could be seen as a partial evolution of ENSGLOSSARY 

I hope this helps

**Comment by jrambla** [comment]
One of the reasons we've choosen that branch of `ENSGLOSSARY` is because it is concise (36 terms if I'm right).
We'll look if we can get a similar solution from `SO`.

**Comment by mbaudis** [comment]
We've addressed this in https://github.com/ga4gh-beacon/beacon-v2/pull/22 - pls. check.

**Comment by mbaudis** [comment]
Closing since solved in #22
