### ISSUE TITLE
Github branching model

### ISSUE THREAD

**Issue by jrambla** [ga4gh-beacon/beacon-v2#18]
During today's GA4GH call, David Salgado has shared the versioning protocol I was referring to and with which many should be familiar.
[](https://git-flow.readthedocs.io/en/latest/presentation.html)
We discussed that a model loke that could be overkill, but I was checking that this branching model is having plugins, at least for VSCode and Visual Studio, that could make the process simpler.
Are you having plugins for your developement environment?
Would it be worth to abide to one clear protocol for everyone to follow?

**Comment by mbaudis** [comment]
Not much from my side; highly skeptical of integrated tools myself. But that's just me.

**Comment by mbaudis** [comment]
Does seem stale/specific. Closing.
