### ISSUE TITLE
Unsupported Filters

### ISSUE THREAD

**Issue by Deepthi-v-s** [ga4gh-beacon/beacon-v2#187]
Hi,

Can i please know is there a way to handle the the filters that are not supported by a particular resource, and also when the filter values are not present in the resource that is being queried?

Thanks & regards,
Deepthi

**Comment by jrambla** [comment]
Are you implementing a beacon, and you want to know how to handle requests that you receive but you don't actually support?

**Comment by Deepthi-v-s** [comment]
Yes @jrambla , we are trying to figure out how the beacon should respond under following conditions -

- when user request data using a filter that haven't been implemented.
- filter exists but no value
-filter exists with partial data (not all subjects have this field)

Thanks & regards,
Deepthi

**Comment by mbaudis** [comment]
@Deepthi-v-s This has several components:

1. Beacons (can/should) inform about their supported filters through the `/fitering_terms` endpoint.
2. The protocol itself does not prescribe how the missing value / no hit is disambiguated. E.g. a filter existing in a Beacon instance in _some_ datasets might not be annotated/used for a _given dataset_; so a missing match can also mean "not annotated there", not necessarily "not found in this dataset" - this would be just inconsistent design by the beacon provider but not prohibited by the protocol...
3. A filter which does not exist should lead to an error response; a filter that exists but has no match in your query to a response with `exists: false` (and respective `count: 0`, `results: []` ...)
4. "filter exists with partial data" ... There is no scenario in the API supporting this specifically. However, implementations can e.g. provide a `count` parameter for `filteringTermsResponse` objects and one can evaluate this value... See the `bycon` implementation used e.g. for Progenetix:
    - <https://bycon.progenetix.org/API/#beaconfilteringtermsresponse>
    - <https://progenetix.org/beacon/filtering_terms/>
5. Beacon aggregators can provide mapping mechanisms between vocabularies of different members

Generally this is something to follow up with through interacting with the Beacon Filters Scouts team ... @tb143 @bea-amos

**Comment by mbaudis** [comment]
@jrambla ...

Point 3: Hmmm... Actually we handle it like that, too, and only send an error if there is no filter value (and no other valid query like variants query or test mode). However this doesn't leave an option to disambiguate between a `0` and a `¯\_(ツ)_/¯` (_i.e._ "no clue what this is) response.

Point 4: The question was about "not all individuals have this field" which is relevant e.g. for compound queries w/ multiple filters. Think e.g. breast cancer samples - if sex isn't annotated for many then a missing hit on "male" might not exclude that there are male samples. Yes, we do always emphasize that "Beacon responses should be considered approximations..." etc. **but** implementers might want to design with high precision in mind for their use cases & look for a protocol compliant way to do that (which I assumed was the context).

**Comment by jrambla** [comment]
I don't think point 3 requires desambiguation. I can't remember any query language that distinguishes between these two scenarios.

For point 4, I have the same conclusion... if a database has a null in a column, the response is "no results"... If the curator has a proper mechanism to infer and populate that column, is up to the curator to do so.

We should mimic how SQL or other query languages work.

**Comment by mbaudis** [comment]
I have added 2 points to the FAQ docs. Closing this here.

<https://genomebeacons.org/FAQ/>
