### ISSUE TITLE
Should we stick to the current combination of schema definition languages - a.k.a. A case for OpenAPI?

### ISSUE THREAD

**Issue by jrambla** [ga4gh-beacon/beacon-v2#30]
The current framework is using two different schema definition languages:

1. OpenAPI 3.0.2 for actual API endpoint definitions. To keep consistency with the Beacon v2 draft1+
2. Json Schema draft07, for any schema that is not an API endpoint. Version 'draft07' was chosen as it is the one supported by OpenAPI 3.0.2

The topic for discussion is, _in the next version_ (minor or major):

1. Makes sense to keep OpenAPI? or could/should we go just for Json Schema?
2. Should we keep the compatibility between OA and JS? or could we update JS to the latest version as they are used quite independently in the Framework?

**Comment by mbaudis** [comment]
@jrambla , all - this issue may serve to re-start other OpenAPI discussions.

**Comment by mbaudis** [comment]
This has now been re-factored into a discussion https://github.com/ga4gh-beacon/beacon-v2/discussions/40

Closing.
