### ISSUE TITLE
pagination should not be required parameter in beaconReceivedRequestSummary

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-beacon/beacon-v2#51]
Pagination should not be required parameter in beaconReceivedRequestSummary since it doesn't make sense in Boolean and count responses (and also not if all data is returned but here YMMV).

https://github.com/ga4gh-beacon/beacon-v2/blob/eb8958fad3a04499d41f7f528292d29d2f23ccbf/framework/src/responses/sections/beaconReceivedRequestSummary.yaml#L50

**Comment by jrambla** [comment]
This issue is also discussed in the issue #55
