### ISSUE TITLE
Explanation on ERD

### ISSUE THREAD

**Issue by anuradhawick** [ga4gh-beacon/beacon-v2#80]
Greetings,

In my understanding, we should be able to have cohorts defined under different criteria such as study, described in beacon or user-defined (I guess this is done using ontology terms).

In these scenarios, having a particular individual referenced across several cohorts is inevitable. However, from the ETD diagram, it seems the cohort-individual relationship has cardinality `1 -<> n` or *one to many*. Could you kindly elaborate on this design aspect? I have attached the ERD for reference.

Thanks
<img width="390" alt="ERD" src="https://user-images.githubusercontent.com/9621844/236721883-e2b41bd3-f202-4fc5-a600-d7c56625a9c1.png">

**Comment by mbaudis** [comment]
@anuradhawick I'd say this is just ill defined. `dataset`s and `cohort`s are 2 types of "collections"; datasets are "physical" groups (e.g. with common access, DAC, storage ... based on the variants) while cohorts can be flexible collections related to groupings of e.g. phenotype, diseases, studies...

We do not model all entity relationships for such parameters. E.g. a cohort may be assembled from members of multiple datasets - though such definitions are pushed out to cohort definitions beyond the Beacon model.

I'll adjust the cohorts<-->individuals to many-to-many ...

**Comment by anuradhawick** [comment]
Thanks for the prompt response and explanation. I will close this issue now.
