### ISSUE TITLE
ResultsOKResponse in collections (cohorts & datatypes)

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/beacon-v2#98]
Hi all,

According the specification, the endpoints [/cohorts/{id}](https://github.com/ga4gh-beacon/beacon-v2/blob/d2be0e2fcc4cbbaebb355caaf8a20af25504a687/models/json/beacon-v2-default-model/cohorts/endpoints.json#L166) and [/datasets/{id}](https://github.com/ga4gh-beacon/beacon-v2/blob/d2be0e2fcc4cbbaebb355caaf8a20af25504a687/models/json/beacon-v2-default-model/datasets/endpoints.json#L164) should return usual ResultsOKResponse (not CollectionsResponse).

This is not what the reference implementation currently does:  
https://ega-archive.org/test-beacon-apis/cineca/cohorts/CINECA_synthetic_cohort_UK1  
https://ega-archive.org/test-beacon-apis/cineca/datasets/CINECA_synthetic_cohort_EUROPE_UK1  

Is this the error in the specification?

Cheers,

Dmitry

**Comment by costero-e** [comment]
Sorry @redmitry , I did not understand your question. But as this is more reference implementation issue, can we please continue this discussion by private message? Thank you!
