### ISSUE TITLE
pagination skip parameter

### ISSUE THREAD

**Issue by redmitry** [ga4gh-beacon/beacon-v2#99]
Hi all,

Current specification defines the ["skip"](https://github.com/ga4gh-beacon/beacon-v2/blob/d2be0e2fcc4cbbaebb355caaf8a20af25504a687/framework/json/common/beaconCommonComponents.json#L232) parameter in terms of pages ("number of **pages** that has been skipped"). This is not that the implementation currently do.
Moreover, this definition poses the limitation in getting data back i.g. "skip first 100 entries":
- skip=1&limit=100 should return the second page (100-200)
- skip =100&limit=0 makes no sense as we have no page size (infinite).

As far as I understand, current implementations use items (not page) counts.

best,

Dmitry

**Comment by mbaudis** [comment]
@redmitry Shouldn't this be an issue for the reference implementation, then? We've implemented it in `bycon` according to the spec (skip means number of pages). I don't mind either way & would go with a) a commonly used standard, b) what the spec now says.

@jrambla ...

**Comment by costero-e** [comment]
Thank you @redmitry for spotting this. In reference implementation we have the mongoDB default skip and limit parameters. We will update the reference implementation to make skip and limit work like specifications. You can mail me anytime you see an issue with the reference implementation @redmitry, it would be preferable so we don't flood GitHub with issues related to reference implementation! I will tell you when I have updated reference implementation. Closing this issue.
